version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp

hooks:
  BeforeInstall:
    - runas: root
      timeout: 300
      commands:
        - echo "Removing old files..."
        - mkdir -p /var/www/myapp
        - rm -rf /var/www/myapp/*
        - echo "Old files removed"

  AfterInstall:
    - runas: root
      timeout: 300
      commands:
        - echo "Installing Node.js..."
        - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
        - yum install -y nodejs
        - echo "Node.js installed"
        - echo "Installing npm packages..."
        - cd /var/www
        - npm init --yes
        - npm install -g serve
        - echo "npm packages installed"
        - echo "Unzipping file..."
        - cd /var/www/myapp
        - yum install -y unzip
        - unzip build

  ApplicationStart:
    - runas: root
      timeout: 300
      commands:
        - echo "Starting the application..."
        - cd /var/www
        - npx serve -s myapp -l 3000
        - echo "Application started"

  ApplicationStop:
    - runas: root
      timeout: 300
      commands:
        - echo "Stopping the application..."
        - pkill -f 'serve'
        - echo "Application stopped"

  ValidateService:
    - runas: root
      timeout: 300
      commands:
        - echo "Validating service..."
        - curl -s http://localhost:3000 || exit 1
        - echo "Service validation passed"