version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - curl -sL https://rpm.nodesource.com/setup_16.x | bash -
      - yum install -y nodejs
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing build artifacts...
      - mv appspec.yml build

artifacts:
  files:
    - '**/*'
  base-directory: build/
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'