
version: '3'

services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
