version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_container
    ports:
      - "8080:8080"    # Expose Jenkins web UI port
      - "50000:50000"  # Port for Jenkins slave agents
    volumes:
      - jenkins_data:/var/jenkins_home  # Persistent data volume
    restart: always    # Automatically restart the container on failure or reboot

volumes:
  jenkins_data:
    driver: local       # Explicitly specify the volume driver (default is `local`)